name: Build Python executable

on:
  push:
    branches:
      - main

jobs:
  build:
    # Используем Windows для сборки .exe
    runs-on: windows-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Шаг 3: Установка зависимостей (PyInstaller)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      # Шаг 4: Сборка .exe файла (используем новый файл `phyzika.py`)
      - name: Build executable
        run: |
          pyinstaller --onefile --distpath ./output .github/workflows/phyzika.py
        # Вывод логов сборки для диагностики
        continue-on-error: false

      # Шаг 5: Проверка наличия .exe файла
      - name: Check if EXE was created
        run: |
          if [ -f "./output/phyzika.exe" ]; then echo "EXE file created successfully!"; else echo "EXE file not found!"; exit 1; fi

      # Шаг 6: Загрузка собранного .exe файла как артефакта
      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: your-executable
          path: output/phyzika.exe

