name: Build Python executable

on:
  push:
    branches:
      - main

jobs:
  build:
    # Используем Windows для сборки .exe
    runs-on: windows-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Шаг 3: Установка зависимостей (PyInstaller)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      # Шаг 4: Сборка .exe файла
      - name: Build executable
        run: |
          pyinstaller --onefile --distpath ./output .github/workflows/phyzika.py
        continue-on-error: false

      # Шаг 5: Проверка наличия .exe файла с помощью PowerShell
      - name: Check if EXE was created
        run: |
          if (Test-Path "./output/phyzika.exe") {
            Write-Host "EXE file created successfully!"
          } else {
            Write-Host "EXE file not found!"
            exit 1
          }

      # Шаг 6: Загрузка собранного .exe файла как артефакта
      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: your-executable
          path: output/phyzika.exe
